apiVersion: apps/v1
kind: Deployment
metadata:
  name: magtape
  labels:
    app: magtape
spec:
  replicas: 3
  selector:
    matchLabels:
      app: magtape
  template:
    metadata:
      labels:
        app: magtape
    spec:
      serviceAccountName: magtape-sa
      containers:
      - name: magtape
        image: tmobile/magtape:2.0.0
        ports:
        - containerPort: 5000
        command: [/app/magtape.py]
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 128Mi
        env:
        - name: MAGTAPE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MAGTAPE_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: magtape-env-cm
        volumeMounts:
          - name: script
            mountPath: /app
          - name: certs
            mountPath: /app/ssl
            readOnly: true
      - name: opa
        image: openpolicyagent/opa:0.16.1
        args:
          - "run"
          - "--server"
          - "--tls-cert-file=/app/ssl/cert.pem"
          - "--tls-private-key-file=/app/ssl/key.pem"
          - "--addr=0.0.0.0:443"
          - "--addr=http://127.0.0.1:8181"
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
          - name: certs
            mountPath: /app/ssl
            readOnly: true
      - name: kube-mgmt
        image: openpolicyagent/kube-mgmt:0.10
        args:
          - "--policies=magtape-system"
          - "--require-policy-label=true"
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 128Mi
      volumes:
        - name: script
          configMap:
            name: magtape-cm
            defaultMode: 0755
            items:
              - key: script
                path: magtape.py
        - name: certs
          secret:
            secretName: magtape-certs
      terminationGracePeriodSeconds: 5