apiVersion: v1
kind: Service
metadata:
  labels:
    app: magtape
  name: magtape-svc
spec:
  ports:
  - name: https
    port: 443
    targetPort: 5000
  selector:
    app: magtape
  sessionAffinity: None
  type: ClusterIP
