apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy04
  labels:
    app: test-deploy04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deploy04
  template:
    metadata:
      labels:
        app: test-deploy04
    spec:
      containers:
      - name: test-deploy04
        image: k8s.gcr.io/liveness
        args:
        - /server
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
            - name: X-Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          limits:
            cpu: "50m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "128Mi"
