{
 "title": "MagTape Cluster Stats",
 "tags": [ "magtape" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Global Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Requests Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_requests_total{count_type=\"total\"})"
    }
   ]
  },
  {
   "title": "Cluster Requests Allowed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_requests_total{count_type=\"allowed\"})"
    }
   ]
  },
  {
   "title": "Cluster Requests Denied",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_requests_total{count_type=\"denied\"})"
    }
   ]
  },
  {
   "title": "Alerts Sent",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_requests_total{count_type=\"total\", alert_sent=\"true\"})"
    }
   ]
  },
  {
   "title": "Cluster Policy Totals",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(policy)(magtape_policy_total{count_type=\"total\"})",
     "legendFormat": "{{policy}}"
    }
   ]
  },
  { "title": "API Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(magtape_http_request_duration_seconds_count{status=\"200\"}[1m]))"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(magtape_http_request_total{status!=\"200\"}[5m])) /\nsum(rate(magtape_http_request_total[5m]))",
     "legendFormat": "Error Percent"
    }
   ]
  },
  { "title": "Resource Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"magtape-svc\"})",
     "legendFormat": "magtape"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pod_name:container_cpu_usage:sum{pod_name=~\"magtape.*\"})"
    }
   ]
  }
 ]
}