{
 "title": "MagTape Namespace Stats",
 "tags": [ "magtape" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(ns)" }
  ]
 },
 "panels": [
  { "title": "$namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "namespace" },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_requests_total{count_type=\"total\", ns=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Allowed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_requests_total{count_type=\"allowed\", ns=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Denied",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_requests_total{count_type=\"denied\", ns=\"$namespace\"})"
    }
   ]
  },
  { "title": "$namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_requests_total{count_type=\"total\", ns=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Allowed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_requests_total{count_type=\"allowed\", ns=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Denied",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_requests_total{count_type=\"denied\", ns=\"$namespace\"})"
    }
   ]
  }
 ]
}