{
 "title": "MagTape Policy Stats",
 "tags": [ "magtape" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "policy", "query": "label_values(policy)" },
   { "name": "namespace", "query": "label_values(ns)" }
  ]
 },
 "panels": [
  { "title": "$policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "policy" },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_policy_total{count_type=\"total\", policy=~\"$policy\", ns=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pass",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_policy_total{count_type=\"pass\", policy=~\"$policy\", ns=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_policy_total{count_type=\"fail\", policy=~\"$policy\", ns=~\"$namespace\"})"
    }
   ]
  },
  { "title": "$policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_policy_total{count_type=\"total\", policy=~\"$policy\", ns=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pass",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_policy_total{count_type=\"pass\", policy=~\"$policy\", ns=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_policy_total{count_type=\"fail\", policy=~\"$policy\", ns=~\"$namespace\"})"
    }
   ]
  },
  { "title": "$policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_policy_total{count_type=\"total\", policy=~\"$policy\", ns=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pass",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_policy_total{count_type=\"pass\", policy=~\"$policy\", ns=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_policy_total{count_type=\"fail\", policy=~\"$policy\", ns=~\"$namespace\"})"
    }
   ]
  },
  { "title": "$policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_policy_total{count_type=\"total\", policy=~\"$policy\", ns=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pass",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_policy_total{count_type=\"pass\", policy=~\"$policy\", ns=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_policy_total{count_type=\"fail\", policy=~\"$policy\", ns=~\"$namespace\"})"
    }
   ]
  },
  { "title": "$policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_policy_total{count_type=\"total\", policy=~\"$policy\", ns=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pass",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_policy_total{count_type=\"pass\", policy=~\"$policy\", ns=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magtape_policy_total{count_type=\"fail\", policy=~\"$policy\", ns=~\"$namespace\"})"
    }
   ]
  }
 ]
}