name: image-build

on:
  release:
    types: [published]

# Jobs
jobs:
  # Build and push magtape-init container image
  build-magtape-init-image:
    name: Push magtape-init image to DockerHub using release tag
    runs-on: ubuntu-latest

    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push release tag to Docker Hub
        if: github.repository == 'tmobile/magtape'
        timeout-minutes: 10
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          path: ./app/magtape-init/
          repository: tmobile/magtape-init
          tag_with_ref: true

      - name: Push magtape-init image to DockerHub using latest tag
        if: github.repository == 'tmobile/magtape'
        timeout-minutes: 10
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          path: ./app/magtape-init/
          repository: tmobile/magtape-init
          tags: latest

  # Build and push magtape container image
  build-magtape-image:
    name: Push magtape image to DockerHub using release tag
    runs-on: ubuntu-latest

    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push release tag to Docker Hub
        if: github.repository == 'tmobile/magtape'
        timeout-minutes: 10
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          path: ./app/magtape/
          repository: tmobile/magtape
          tag_with_ref: true

      - name: Push magtape-init image to DockerHub using latest tag
        if: github.repository == 'tmobile/magtape'
        timeout-minutes: 10
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          path: ./app/magtape/
          repository: tmobile/magtape
          tags: latest
