name: ci-manifest-checks

on: 
  pull_request:
    # Commenting out paths for now until GH Actions
    # Have good suport for required checks + path filters
    # https://github.community/t5/GitHub-Actions/Feature-request-conditional-required-checks/m-p/36938#M2735
    #paths:
    #  - 'deploy/**'

# Jobs
jobs:
  # Job to check for manifest changes
  compare-manifests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check for manifest changes
      run: |
        make compare-install-manifest