name: ci-python-checks

on: [pull_request]

# Jobs
jobs:
  # Job to lint code
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Lint with Black
      run: |
        pip install black
        make ci-lint
  # Job to execute unit tests
  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        export PIPENV_PIPFILE="app/magtape/Pipfile"
        pipenv install --system --deploy
        export PIPENV_PIPFILE="app/magtape-init/Pipfile"
        pipenv install --system --deploy

    - name: Test with unittest
      run: |
        make test